baseURL = "https://www.ferndrang.de/"
languageCode = "de"
title = "ferndrang"
disableKinds = ["RSS"]

[params]
  author = "A. Zeisler & F. Hassert"

  # Cloudinary Configuration
  cloudinaryBaseURL = "https://res.cloudinary.com/ferndrang/image/upload"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[permalinks]
  [permalinks.section]
    journeys = "/:slug/"
  [permalinks.page]
    journeys = "/:slug/"
